### ISSUE TITLE
Research product - "role" and "contribution"

### ISSUE THREAD

**Issue by rduyme** [skg-if/interoperability-framework#11]
In https://skg-if.github.io/interoperability-framework/research-product
we have :

- role String (recommended): The role that an [Agent](https://skg-if.github.io/interoperability-framework/agent) had in the [Research product](https://skg-if.github.io/interoperability-framework/research-product), to choose among author, editor, and publisher.
- contribution List (recommended): The contributions that an [Agent](https://skg-if.github.io/interoperability-framework/agent) had in the [Research product](https://skg-if.github.io/interoperability-framework/research-product). Each element in the list is a String compliant with the [CRediT taxonomy](https://credit.niso.org/), i.e., conceptualization, data curation

In Datacite there is a simple way to separate "creators" and "contributors" (2 distinct arrays).  It is commonly used to have clear distinction of "authors" and people involved without being actual authors. 
For example, we use Datacite contributors to list facility experiment local contacts, helping our user to perform experiments. 
see : https://datacite-metadata-schema.readthedocs.io/en/4.5/properties/contributor/#  (Datacite also has a contributor a bit similar to CRediT taxonomy)

I suppose we would use.
- skg-if role "author" for datacite creators
- what skg-if role would fit to express datacite "contributors" . null value  ?

**Comment by essepuntato** [comment]
An agent contributes to a research object if it appears within the field `contributions`. Being an author, thus putting it explicitly using the field `role`, enables one to assign a specific role to the agent involved in the research product. If it does not have the role of author (neither editor nor publisher), then one does not have to specify the field `role`.

**Comment by rduyme** [comment]
Ok I understand. If an Agent is not an "author", "publisher" or "editor" do not feed the role. 
Still we need at least definitions, inline doc example  for "author", "editor" or "publisher" 

The "editor" term is used in Venue as well.  (as Journal editor), 
but  "editor" in  "Research Product", I don't fully get what we expect. is it someone editing (writing the research article and not an author ? 

https://en.wikipedia.org/wiki/Editor_(disambiguation)
