### ISSUE TITLE
Doc issue : link "Research Product" => "Data Source",  "Research Product" => "Venue"

### ISSUE THREAD

**Issue by rduyme** [skg-if/interoperability-framework#12]
Hi .

in https://skg-if.github.io/interoperability-framework/research-product

we have :
 
* in String (optional): A [Venue](https://skg-if.github.io/interoperability-framework/venue) identifier for the manifestation.
* hosting_data_source String (optional): A Data source URL for the manifestation.

where is the actual link with the Data Source entity ? https://skg-if.github.io/interoperability-framework/data-source

It was different in v1.1 https://skg-if.readthedocs.io/en/v1.1/products.html#manifestations
* venue String (optional): A [Venue](https://skg-if.readthedocs.io/en/v1.1/venues.html#venue) identifier for the manifestation.
* hosting_data_source String (optional): A [Data source](https://skg-if.readthedocs.io/en/v1.1/datasources.html#data-source) identifier for the manifestation.`

**Comment by rduyme** [comment]
On new graphs : https://github.com/skg-if/data-model/blob/main/docs/index.md 

I don't see the "Research Product" => "Venue" link

![image](https://github.com/user-attachments/assets/c20520e6-b79a-4579-b51f-a17278e66391)

**Comment by essepuntato** [comment]
The link between the research product and its venue happens via the `manifestations` field (see the field `in` there). In the data model, such a link is performed the class fabio:Expression, that is connected to the fabio:Work representing a our SKG-IF research product.
