### ISSUE TITLE
Add a text explaining how local_identifier works under the hood

### ISSUE THREAD

**Issue by andremann** [skg-if/interoperability-framework#2]
This needs to be added for every entity before the example.

**Comment by essepuntato** [comment]
A text has been added in the index to explain the overall rationale of the `local_identifier`. All the DKG-IF entities have been updated by referring to such text for further explanation. Related commit: https://github.com/skg-if/interoperability-framework/commit/00d0f99da6a316b0fb6eb4e0808ae60366b82cf2
