### ISSUE TITLE
Grant local_id could cause clashes. Add grant code

### ISSUE THREAD

**Issue by andremann** [skg-if/interoperability-framework#4]
grant.local_identifier, grant.grant_no
The definition of the local_identifier is “Unique code identifying the Grant at the funder.” This may in some cases lead to the situation that there are two or more grant instances having the same local_identifier in one SKG. Even if the code is unique for a funder it does not mean that it is unique globally. Also there are (small and national) funders that do not give any public IDs for grants e.g. https://koneensaatio.fi/en/ . 

Proposition : It would be better to have two distinct fields:
local_identifier: Unique code identifying the grant in the SKG (mandatory)
grant_no (or grant_identifier, award_id) : Unique code identifying the Grant at the funder. (optional)
Website (optional)

**Comment by essepuntato** [comment]
Agreed. I've used the terminology in [FRAPO](https://w3id.org/spar/frapo), and specified `grant_number` in the JSON-LD context. The modification has been introduced in the [current (i.e. working) version](https://github.com/skg-if/context/tree/main/ver/current) of the context, which should be crystallised in a release in the following days.

It has been added in commit https://github.com/skg-if/context/commit/3d721e63ee936fb2de11e0f1ae5e11648db2d468.
