### ISSUE TITLE
Id schemes depending on the kind of entity

### ISSUE THREAD

**Issue by essepuntato** [skg-if/interoperability-framework#9]
In the documentation, we should specify the possible schemes for identifiers. In addition, it would be important also to have a "local identifier scheme" which allows someone to specify a particular id scheme which is used only locally to the data source.

**Comment by rduyme** [comment]
Science on Schema.org (working group to express datasets with schema.org ) recommends using identifiers.org as reference. 

https://github.com/ESIPFed/science-on-schema.org/blob/main/guides/Dataset.md#identifier 

Note : The same kind of recommendation is done for licenses :https://github.com/ESIPFed/science-on-schema.org/blob/main/guides/Dataset.md#license

**Comment by essepuntato** [comment]
Identifiers.org only contains some of the identifiers we need. We are using the [DataCite SPAR Ontologies](https://w3id.org/spar/datacite) instead as a reference – that we can extend easily in case new identifiers are coming out.

**Comment by rduyme** [comment]
Ok no problem Silvio, I am focused on clarification regarding implementation and guiding the devs.
Can we add https://skg-if.github.io/interoperability-framework/docs/research-product.html#identifiers

"The full list of supported schemes are defined in https://sparontologies.github.io/datacite/current/datacite.html "
